project_id = "findat-consultants"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[storage]
enabled = true
file_size_limit = "50MiB"
