import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const json=(p)=>JSON.parse(read(p));
function check(ok,label,detail=''){if(!ok){console.error(`FAIL ${label}${detail?`: ${detail}`:''}`);process.exitCode=1;}else console.log(`PASS ${label}${detail?`: ${detail}`:''}`);}
const live=json('data/live-system-data.json'),mts=json('data/mts-runtime.json'),training=json('data/training/workbook-demo-reference.json');
check(Object.values(live).every(v=>Array.isArray(v)&&v.length===0),'clean live operational state');
check(Array.isArray(mts.sessions)&&mts.sessions.length===0,'clean Work Activity Hub runtime');
check(training.classification==='TRAINING_REFERENCE_ONLY'&&training.authority==='NON_LIVE_NON_POSTING','historical data isolated as training reference');
const html=read('public/index.html'),app=read('public/app.js'),store=read('src/live-data-store.js'),server=read('server.js');
check(!html.includes('workbook-data.js'),'historical workbook data not shipped to browser');
check(!html.match(/471 time records|Engine reconciled|Prototype mode/i),'prototype status/data removed from front end');
check(html.indexOf('data-view="company"')>html.indexOf('data-view="dashboard"') && html.indexOf('data-view="company"')<html.indexOf('data-view="assistant"'),'Company is positioned between Dashboard and Recovery Agent');
check(html.includes('Company Structure')&&html.includes('companyAddEmployeeBtn')&&app.includes('renderCompany'),'Company organization workspace is enabled');
check(app.includes('department:$(') && app.includes('team:$('),'Company employee capture feeds department/team master data');
check(html.includes('companyEmployeePhoto')&&html.includes('employeePhotoInput'),'profile picture capture enabled in Company and Employees');
check(app.includes('optimizeProfilePhoto')&&app.includes('userIdentity('),'profile picture optimization and reusable user identity rendering enabled');
check(store.includes('profilePhoto'),'profile picture persists in the live employee backend record');
check(app.includes('userIdentity(x.employee_id,x.employee_name')&&app.includes('userIdentity(r.employeeId'),'profile identity propagated to Work Activity Hub and Payroll');
check(app.includes('TABLE_PAGE_SIZE=10'),'all table paginator capped at 10 rows');
check(html.includes('data-view="recruiting"')&&html.includes('data-view="onboarding"'),'Recruiting and Onboarding navigation enabled');
check(html.includes('recruitFunnel')&&app.includes('renderRecruitFunnel'),'live recruitment funnel enabled');
check(html.includes('onboardingWizard')&&app.includes('moveOnboarding'),'guided onboarding workflow enabled');
check(store.includes('upsertLiveVacancy')&&store.includes('upsertLiveCandidate')&&store.includes('upsertLiveOnboarding'),'people-operations records persist in live backend state');
check(store.includes("status:'Hired'")&&store.includes('engine.upsertEmployee'),'completed onboarding promotes candidate into employee master');
check(app.includes('employeeDirectorySearch')&&app.includes('employee-status'),'employee directory visual/filter layer enabled');
check(app.includes('Waiting for live data'),'dashboard has live-data zero-state visualization');
check(store.includes('Auto-created from Work Activity Hub'),'Work Activity Hub creates live calendar context');
check(store.includes('Awaiting payroll input — created by Work Activity Hub'),'Work Activity Hub creates payroll completion placeholder');
check(store.includes('Work Activity Hub completed hours'),'Work Activity Hub drives source reconciliation');
check(server.includes('/api/live/state'),'live state API enabled');
check(!server.includes("req.query.month||'2026-06'")&&!server.includes("req.query.project||'ASPIRE'"),'demo voucher defaults removed');
const control=read('src/control-center-store.js'),currencies=read('public/currencies.js');
check(html.includes('controlDock')&&html.includes('notificationBadge')&&html.includes('documentBadge')&&html.includes('reviewBadge')&&html.includes('dockProfileAvatar'),'dashboard top-center control dock enabled');
check(server.includes('/api/control-center')&&server.includes('/api/control-center/reviews/:id/action'),'control-center and assigned review APIs enabled');
check(control.includes('PENDING_REVIEW')&&control.includes('automaticDocumentAnalysis')&&control.includes('approved-documents'),'document inbox, automated pre-screen and approved archive enabled');
check(control.includes('assignedToActor')&&(control.includes('This review belongs to another company or administrator')||control.includes('Only an Administrator of this company may review this document')),'review actions restricted to assigned users and company');
check(server.includes('/api/mts/messages/:id/read')&&app.includes('markControlMessageRead'),'unread messages clear through read-state workflow');
check(currencies.includes('ADRA_CURRENCIES')&&app.includes('settingsCurrencyCountry')&&app.includes('defaultHourlyRate'),'country/currency and hourly-rate settings enabled');
check(app.includes('hourlyRateFor')&&app.includes('hourlyCostFor'),'hourly-rate settings connected to operational cost displays');
check(html.includes('controlSignOut')&&server.includes('/api/control-center/logout'),'profile sign-out enabled');
check(app.includes('bindCloseButtons')&&html.includes('controlDrawerClose'),'close controls wired');
check(html.includes('clearAgentConversation')&&html.includes('newAgentConversation')&&app.includes('clearAgentConversation'),'Recovery Agent clear/new conversation controls enabled');
if(!process.exitCode)console.log('\nUnified live Work Activity Hub + Recovery Passport verification passed.');
