-- ADRA Recovery Passport — persistent agent memory, sessions, stored records and audit actions
-- Prototype mode has no browser sign-in. These tables are intended to be accessed server-side
-- through the application's Supabase secret/service role. Add RLS policies when user auth is enabled.

create table if not exists public.agent_memories (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text not null default 'fact',
  authority text not null default 'CONFIRMED',
  importance numeric(4,3) not null default 0.700 check (importance >= 0 and importance <= 1),
  source_type text not null default 'system',
  source_ref text not null default '',
  tags jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  session_id text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_used_at timestamptz,
  use_count integer not null default 0
);

create index if not exists agent_memories_category_idx on public.agent_memories(category);
create index if not exists agent_memories_authority_idx on public.agent_memories(authority);
create index if not exists agent_memories_updated_idx on public.agent_memories(updated_at desc);

create table if not exists public.agent_session_items (
  id bigint generated by default as identity primary key,
  session_id text not null,
  sequence bigint not null,
  item jsonb not null,
  created_at timestamptz not null default now(),
  unique(session_id, sequence)
);
create index if not exists agent_session_items_session_idx on public.agent_session_items(session_id, sequence);

create table if not exists public.system_records (
  id bigint generated by default as identity primary key,
  record_type text not null default 'note',
  title text not null,
  content text not null,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  source text not null default 'system',
  session_id text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists system_records_type_idx on public.system_records(record_type);
create index if not exists system_records_status_idx on public.system_records(status);
create index if not exists system_records_updated_idx on public.system_records(updated_at desc);

create table if not exists public.agent_action_log (
  id bigint generated by default as identity primary key,
  session_id text not null default '',
  action_name text not null,
  input_data jsonb not null default '{}'::jsonb,
  result_data jsonb not null default '{}'::jsonb,
  status text not null default 'completed',
  created_at timestamptz not null default now()
);
create index if not exists agent_action_log_created_idx on public.agent_action_log(created_at desc);
create index if not exists agent_action_log_session_idx on public.agent_action_log(session_id, created_at desc);

-- Initial durable design memory. Numeric calculations still come from the deterministic engine.
insert into public.agent_memories(title,content,category,authority,importance,source_type,source_ref,tags)
select * from (values
  ('Recovery Passport five-key gate', 'A proposed personnel charge is recoverable only when Evidence, Capacity, Eligibility, Budget and Approval all pass. One failed key blocks posting while the underlying cost remains visible.', 'policy', 'FOUNDATIONAL', 1.000, 'source_document', 'Cost Recovery.docx', '["recovery passport","control gate"]'::jsonb),
  ('Deterministic financial authority', 'Hours, payroll allocation, eligibility, formula results, posting status, Recovery Gate and voucher amounts must come from the embedded deterministic workbook engine rather than model invention.', 'policy', 'FOUNDATIONAL', 1.000, 'system_design', 'Workbook engine', '["authority","calculation"]'::jsonb),
  ('AI role boundary', 'AI may suggest projects, classify activities, explain exceptions, detect unusual patterns, draft follow-ups and summarize risks. AI may not change hours, approve time, determine salary, override donor restrictions or authorize journal entries.', 'policy', 'FOUNDATIONAL', 1.000, 'source_document', 'Cost Recovery.docx', '["AI","controls"]'::jsonb),
  ('Learning from confirmed decisions', 'The application may learn from repeated human-confirmed activity coding decisions, but it must continue to show the suggestion and confidence instead of silently posting a learned code.', 'lesson', 'FOUNDATIONAL', 0.950, 'source_document', 'Cost Recovery.docx', '["learning","coding"]'::jsonb)
) as v(title,content,category,authority,importance,source_type,source_ref,tags)
where not exists (select 1 from public.agent_memories m where m.title=v.title);

-- Server-only persistence boundary. Browser roles have no direct table access.
alter table public.agent_memories enable row level security;
alter table public.agent_session_items enable row level security;
alter table public.system_records enable row level security;
alter table public.agent_action_log enable row level security;

revoke all on table public.agent_memories from anon, authenticated;
revoke all on table public.agent_session_items from anon, authenticated;
revoke all on table public.system_records from anon, authenticated;
revoke all on table public.agent_action_log from anon, authenticated;

grant all on table public.agent_memories to service_role;
grant all on table public.agent_session_items to service_role;
grant all on table public.system_records to service_role;
grant all on table public.agent_action_log to service_role;
