begin;

-- FINDAT Storage is served through short-lived S3 presigned URLs generated by
-- the server-side Edge Function. Keep the bucket private while retaining
-- the existing Storage RLS policies as an automatic REST fallback.
update storage.buckets
set public = false,
    file_size_limit = 52428800
where id = 'findat-documents';


comment on table public.findat_documents is
  'FINDAT PostgreSQL document catalogue. Actual file bytes are stored in the private findat-documents bucket and accessed through the findat-s3 Edge Function.';

commit;
